// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO89RLtW2TUUNrNfsf4aLZ-7fy45cwAL8',
    appId: '1:1043229933176:web:1d71851fb25af755b3f78d',
    messagingSenderId: '1043229933176',
    projectId: 'namdelivery-db436',
    authDomain: 'namdelivery-db436.firebaseapp.com',
    storageBucket: 'namdelivery-db436.firebasestorage.app',
    measurementId: 'G-3D52QFSM01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBligg3anTNjoFf9MAgCBv6SqbC_AuLq5A',
    appId: '1:1043229933176:android:03002c4a6e5cddaeb3f78d',
    messagingSenderId: '1043229933176',
    projectId: 'namdelivery-db436',
    storageBucket: 'namdelivery-db436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU3bsSIAV-EArO98YCv23260OVzS5jd6A',
    appId: '1:1043229933176:ios:a6ca61448f086680b3f78d',
    messagingSenderId: '1043229933176',
    projectId: 'namdelivery-db436',
    storageBucket: 'namdelivery-db436.firebasestorage.app',
    iosBundleId: 'com.workahr.namfooddelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU3bsSIAV-EArO98YCv23260OVzS5jd6A',
    appId: '1:1043229933176:ios:a6ca61448f086680b3f78d',
    messagingSenderId: '1043229933176',
    projectId: 'namdelivery-db436',
    storageBucket: 'namdelivery-db436.firebasestorage.app',
    iosBundleId: 'com.workahr.namfooddelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO89RLtW2TUUNrNfsf4aLZ-7fy45cwAL8',
    appId: '1:1043229933176:web:a92f3a3bb674ff02b3f78d',
    messagingSenderId: '1043229933176',
    projectId: 'namdelivery-db436',
    authDomain: 'namdelivery-db436.firebaseapp.com',
    storageBucket: 'namdelivery-db436.firebasestorage.app',
    measurementId: 'G-1PDG4JR53V',
  );
}
